### ISSUE TITLE
Sample example 

### ISSUE THREAD

**Issue by DerXanRam** [moonbeam-foundation/cli-ts-signer#30]
Hello bro. I am trying swap on Uniswapv2 router 02using  `eth_sendRawTransaction`  RPC-API. and the contract i am trying to sign is ....

```
function swapExactETHForTokens(uint amountOutMin, address[] calldata path, address to, uint deadline)
        external
        payable
        returns (uint[] memory amounts);
```

But i see the examples and it is little bit confusing. Can u give me some examples please?

**Comment by crystalin** [comment]
Hi @DerXanRam , 

Sorry but we don't really maintain the Ethereum signer part of the tool anymore. It still works to sign the message, but we never added features like building/sending the transaction itself. I suppose you could build it in remix, sign the message with this signer and then combine the data to simply send with eth_sendRawTransaction but we don't provider helper for it.

I think some dedicated Ethereum tool would be more useful to achieve what you want
